### ISSUE TITLE
`VersionsFile#gem_lines` NoMethodError

### ISSUE THREAD

**Issue by indirect** [bundler/compact_index#6]
While using the compact_index gem for the Bundler specs, I discovered this NoMethodError:

```
    NoMethodError: undefined method `number_and_platform' for #<Hash:0x000000035ad1a8>
      /home/travis/build/bundler/bundler/tmp/gems/base/gems/compact_index-0.9.3/lib/compact_index/versions_file.rb:94:in `map'
    /home/travis/build/bundler/bundler/tmp/gems/base/gems/compact_index-0.9.3/lib/compact_index/versions_file.rb:94:in `block in gem_lines'
    /home/travis/build/bundler/bundler/tmp/gems/base/gems/compact_index-0.9.3/lib/compact_index/versions_file.rb:92:in `each'
    /home/travis/build/bundler/bundler/tmp/gems/base/gems/compact_index-0.9.3/lib/compact_index/versions_file.rb:92:in `reduce'
    /home/travis/build/bundler/bundler/tmp/gems/base/gems/compact_index-0.9.3/lib/compact_index/versions_file.rb:92:in `gem_lines'
    /home/travis/build/bundler/bundler/tmp/gems/base/gems/compact_index-0.9.3/lib/compact_index/versions_file.rb:77:in `parse_gems_for_create'
    /home/travis/build/bundler/bundler/tmp/gems/base/gems/compact_index-0.9.3/lib/compact_index/versions_file.rb:43:in `create'
    /home/travis/build/bundler/bundler/tmp/gems/base/gems/compact_index-0.9.3/lib/compact_index/versions_file.rb:32:in `update_with'
```

It seems like what is happening is that the `VersionFile` methods `#parse_gems` and `#parse_gems_for_create` both create arrays of hashes, and then pass those arrays of hashes into `gem_lines`. Then, the `gem_lines` method calls the `number_and_platform` method on each list of versions, but those versions are hashes, not structs. Sad face. :(

**Comment by indirect** [comment]
Oops. This was fixed by passing in `CompactIndex::Gem`s and `CompactIndex::GemVersion`s instead of hashes. :grimacing: My bad!
